# Generated by Django 4.0.2 on 2022-02-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Nationality', models.CharField(max_length=255)),
                ('Overall', models.IntegerField()),
            ],
        ),
    ]
